version: "3.7"

services:
  app:
    build:
      context: ./
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7.33
    platform: linux/amd64
    command: "--ignore-db-dir=lost+found"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    ports:
      - 3306

volumes:
  mysql-data:
