
name: Release

# Configures this workflow to run every time a change is pushed to the branch called `main`, or a version tag is pushed.
on:
  push:
    branches: ['main']
    tags:
      - 'v*'

jobs:
  image:
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    uses: appvia-demos/ci-reusable-workflows/.github/workflows/wayfinder-image-release-workflow.yml@main
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}


